apiVersion: certmanager.k8s.io/v1alpha1
kind: Cetificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: lukedonley-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: lukedonley.com
  dnsNames:
    - lukedonley.com
    - www.lukedonley.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - lukedonley.com
          - www.lukedonley.com
